language: python
addons:
    firefox: "49.0"
python:
    - "3.6"
install:
    - "pip install -r requirements.txt"
    - "npm install"
    - "mkdir ../database"
    - "python manage.py migrate"
script:
    - python manage.py test
